### ISSUE TITLE
Question about using etl with sml

### ISSUE THREAD

**Issue by CodingPapi** [adarwoo/cyclo#6]
Hi adarwoo,
thanks for sharing this project, it helps me a lot for learning etl and sml.
I have one question of using etl queue for sml process queue, do you know how to achive this?

Thanks again

**Comment by adarwoo** [comment]
Hello CodingPapi,

Glad to help.

The ETL queue out of the box is just a container unlike an RTOS queue which is a synchronisation item.
However, it can be made into an synchronous queue, leveraging synchronisation objects from your RTOS (mutex, semaphones or condition) by deriving the etl::queue_lockable.

As such, you can combine the ETL queue with SML so that you can push events in the queue, and pop them as transition events for the state machine.

If you do so, a given state machine will be processed by one task, whilst all other tasks may 'push' into the queue to trigger transitions.

Cyclo leverages the OS queue rather than the ETL since I did not do the OS integration of the etl::Queue with the OS (by deriving the etl::queue_lockable.

If you do not have a RTOS, or are using a Sequencer or Reactor pattern, you may still use the etl::Queue providing you pull from queue during one of the sequence, or as part of the reactor loop.

Therefore, this should work nicely I think.

Regards,

Bill (Adarwoo)

**Comment by CodingPapi** [comment]
Thank you for your kindness and great help
